'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {ArrowDown,ArrowUpRight,Pause,Play,RotateCcw,MapPin,Heart} from 'lucide-react';
import type {Invite} from './shared';
import WeddingCountdown from './wedding-countdown';
const dateText=(date:string)=>date?new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'Our wedding day';
export default function EditorialInvitation({data}:{data:Invite}){
 const [stage,setStage]=useState<'closed'|'opening'|'open'>('closed'),[motion,setMotion]=useState(true);const root=useRef<HTMLElement>(null),title=useRef<HTMLHeadingElement>(null);const first=data.first||'Your name',second=data.second||'Your partner';const open=stage==='open';
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(stage!=='opening')return;const timer=setTimeout(()=>setStage('open'),motion?1350:30);return()=>clearTimeout(timer)},[stage,motion]);
 useEffect(()=>{if(!open)return;const timeout=setTimeout(()=>title.current?.focus({preventScroll:true}),100);return()=>clearTimeout(timeout)},[open]);
 useEffect(()=>{if(!open)return;const nodes=root.current?.querySelectorAll('.ed-reveal');if(typeof IntersectionObserver==='undefined'){nodes?.forEach(el=>el.classList.add('ed-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('ed-visible');observer.unobserve(entry.target)}}),{threshold:.08});nodes?.forEach(el=>observer.observe(el));return()=>observer.disconnect()},[open,data.photo,data.story,data.events,data.dressCode,data.accommodation,data.gifts]);
 function tilt(e:PointerEvent<HTMLElement>){if(!motion||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();root.current?.style.setProperty('--ed-x',((e.clientX-r.left)/r.width-.5)*6+'deg');root.current?.style.setProperty('--ed-y',-((e.clientY-r.top)/r.height-.5)*5+'deg')}
 function reset(){root.current?.style.setProperty('--ed-x','0deg');root.current?.style.setProperty('--ed-y','0deg')}
 function replay(){setStage('closed');reset();root.current?.scrollIntoView({behavior:'auto',block:'start'})}
 return <article data-long-names={Math.max(first.length,second.length)>14} ref={root} className={'editorial-invite ed-'+stage+(motion?'':' ed-paused')}>
 <section className="ed-hero" onPointerMove={tilt} onPointerLeave={reset}>
 {data.photo&&<img className="ed-hero-photo" src={data.photo} alt={first+' and '+second} fetchPriority="high"/>}<div className="ed-photo-shade"/>
 <div className="ed-controls"><button onClick={()=>{setMotion(!motion);reset()}} aria-label={motion?'Pause animation':'Resume animation'} aria-pressed={!motion}>{motion?<Pause size={17}/>:<Play size={17}/>}</button>{open&&<button onClick={replay} aria-label="Replay opening"><RotateCcw size={17}/></button>}</div>
 <div className="ed-hero-copy" inert={!open} aria-hidden={!open}><div className="ed-running-head"><span>TOGETHER WITH OUR FAMILIES</span><span>{data.date?data.date.slice(0,4):'FOREVER'}</span></div><div className="ed-title-group"><span className="ed-eyebrow">YOU ARE INVITED TO THE WEDDING OF</span><h1 ref={title} tabIndex={-1}>{first}<span><i>&</i> {second}</span></h1><div className="ed-hero-meta"><span>{dateText(data.date)}</span><span>{data.events.find(e=>e.date===data.date)?.venue||data.events[0]?.venue||'A beautiful beginning'}</span></div><a href="#editorial-countdown" className="ed-discover">The beginning of everything <ArrowDown size={18}/></a></div></div>
 {stage!=='open'&&<div className="ed-cover" inert={stage!=='closed'} aria-hidden={stage!=='closed'}><div className="ed-shutter ed-shutter-left"/><div className="ed-shutter ed-shutter-right"/><div className="ed-cover-copy"><span className="ed-eyebrow">A WEDDING INVITATION</span><div className="ed-cover-monogram">{first[0]}<i>&</i>{second[0]}</div><div className="ed-cover-rule"/><p className="ed-cover-names">{first} <i>&</i> {second}</p><p className="ed-cover-date">{dateText(data.date)}</p><button onClick={()=>setStage('opening')} disabled={stage!=='closed'} className="ed-open-button">Open our story <ArrowUpRight size={18}/></button><span className="ed-cover-foot">THIS IS WHERE OUR FOREVER BEGINS.</span></div></div>}
 <span className="sr-only" role="status">{stage==='opening'?'Opening your invitation…':open?'Your invitation is open.':''}</span>
 </section>
 {open&&<div className="ed-pages"><section className="ed-intro ed-reveal"><span className="ed-eyebrow">ONE DAY. ALL OUR FAVOURITE PEOPLE.</span><h2>Some things are<br/><em>meant to be.</em></h2><p>{data.message||'We would love to celebrate the beginning of our forever with you.'}</p><Heart size={19}/></section>
 <div id="editorial-countdown" className="ed-countdown ed-reveal"><WeddingCountdown data={data}/></div>
 <section className="ed-story ed-reveal"><div className="ed-story-heading"><span className="ed-eyebrow">01 / OUR STORY</span><h2>A chance meeting.<br/><em>A choice, every day.</em></h2></div>{data.photo&&<div className="ed-portrait-stage" onPointerMove={tilt} onPointerLeave={reset}><figure className="ed-portrait" key={data.photo}><img src={data.photo} alt={first+' and '+second+' together'} loading="lazy"/><figcaption><span>{first} & {second}</span><span>EST. {data.date?.slice(0,4)||'FOREVER'}</span></figcaption></figure><span className="ed-portrait-note" aria-hidden="true">always,<br/><i>you.</i></span></div>}<div className="ed-story-body"><span className="ed-dropcap">&</span><p>{data.story||'The little moments brought us here. Now we are ready to write our next chapter, surrounded by the people we love.'}</p>{(data.firstFamily||data.secondFamily)&&<p className="ed-family">{data.firstFamily}<br/>{data.secondFamily}</p>}</div></section>
 <section className="ed-events ed-reveal"><div className="ed-section-heading"><span className="ed-eyebrow">02 / THE CELEBRATION</span><h2>Be part of<br/><em>our best day.</em></h2></div>{data.events.map((event,index)=><article className="ed-event ed-reveal" key={index}><span className="ed-event-number">{String(index+1).padStart(2,'0')}</span><div className="ed-event-copy"><span className="ed-eyebrow">{dateText(event.date)}{event.time?' · '+event.time:''}</span><h3>{event.name||'Our celebration'}</h3><h4>{event.venue||'Venue to be announced'}</h4><p>{event.address}</p>{event.address&&<a className="ed-map" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(event.venue+' '+event.address)} target="_blank" rel="noreferrer"><MapPin size={16}/> Find the venue <ArrowUpRight size={16}/></a>}</div></article>)}</section>
 {(data.dressCode||data.accommodation||data.gifts)&&<section className="ed-details ed-reveal"><span className="ed-eyebrow">THE LITTLE DETAILS</span>{[['Dress code',data.dressCode],['Your stay',data.accommodation],['Gifts',data.gifts]].map(([label,body])=>body&&<div key={label}><h3>{label}</h3><p>{body}</p></div>)}</section>}
 <section className="ed-finale ed-reveal">{data.photo&&<img src={data.photo} alt="" loading="lazy"/>}<div className="ed-finale-shade"/><div className="ed-finale-copy"><span className="ed-eyebrow">THE NEXT CHAPTER IS OUR FAVOURITE.</span><h2>See you<br/><em>at forever.</em></h2><p>{first} <i>&</i> {second}</p><span>{dateText(data.date)}</span></div></section><footer className="ed-footer"><button onClick={replay}>Play it again <RotateCcw size={14}/></button><a href="/">Wedlink</a><span>MADE FOR YOUR STORY.</span></footer></div>}
 </article>
}
