'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {ArrowDown,ArrowUpRight,Heart,MapPin,Pause,Play,RotateCcw,Sparkles} from 'lucide-react';
import type {Invite} from './shared';
import WeddingCountdown from './wedding-countdown';
const dateText=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'Our wedding day';
export default function HeritageInvitation({data}:{data:Invite}){
 const [stage,setStage]=useState<'closed'|'opening'|'open'>('closed');const [motion,setMotion]=useState(true);const root=useRef<HTMLElement>(null);const heading=useRef<HTMLHeadingElement>(null);const open=stage==='open';const first=data.first||'Your name',second=data.second||'Your partner';
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!q.matches);update();q.addEventListener('change',update);return()=>q.removeEventListener('change',update)},[]);
 useEffect(()=>{if(stage!=='opening')return;const timer=setTimeout(()=>setStage('open'),motion?1500:30);return()=>clearTimeout(timer)},[stage,motion]);
 useEffect(()=>{if(!open)return;heading.current?.focus({preventScroll:true});const nodes=root.current?.querySelectorAll('.ht-reveal');if(typeof IntersectionObserver==='undefined'){nodes?.forEach(n=>n.classList.add('ht-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('ht-visible');observer.unobserve(entry.target)}}),{threshold:.06});nodes?.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[open,data.photo,data.story,data.events,data.firstFamily,data.secondFamily,data.dressCode,data.accommodation,data.gifts]);
 function reset(){root.current?.style.setProperty('--ht-x','0deg');root.current?.style.setProperty('--ht-y','0deg')}
 function tilt(e:PointerEvent<HTMLElement>){if(!motion||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();root.current?.style.setProperty('--ht-x',((e.clientX-r.left)/r.width-.5)*8+'deg');root.current?.style.setProperty('--ht-y',-((e.clientY-r.top)/r.height-.5)*5+'deg')}
 function replay(){setStage('closed');reset();root.current?.scrollIntoView({behavior:'auto',block:'start'})}
 return <article ref={root} className={'heritage-invite ht-'+stage+(motion?'':' ht-paused')} data-long-names={Math.max(first.length,second.length)>14}>
 <section className="ht-hero" onPointerMove={tilt} onPointerLeave={reset}>
 <img className="ht-palace" src="/royal-courtyard.png" alt="" fetchPriority="high"/><div className="ht-hero-shade"/>
 <div className="ht-controls"><button aria-label={motion?'Pause animation':'Resume animation'} aria-pressed={!motion} onClick={()=>{setMotion(!motion);reset()}}>{motion?<Pause size={17}/>:<Play size={17}/>}</button>{open&&<button onClick={replay} aria-label="Replay Heritage opening"><RotateCcw size={17}/></button>}</div>
 <div className="ht-folio">
 <div className="ht-letter" inert={!open} aria-hidden={!open}><span className="ht-eyebrow">WITH THE BLESSINGS OF OUR FAMILIES</span><div className="ht-letter-symbol"><Sparkles size={24} strokeWidth={1}/></div><p className="ht-invitation-line">A love to honour.<br/>A lifetime to celebrate.</p><h1 ref={heading} tabIndex={-1}>{first}<i>&</i>{second}</h1><div className="ht-gold-rule"/><p className="ht-letter-date">{dateText(data.date)}</p><p className="ht-letter-venue">{data.events.find(e=>e.date===data.date)?.venue||data.events[0]?.venue||'Together is our favourite place'}</p><span className="ht-eyebrow ht-letter-bottom">YOUR PRESENCE IS OUR GREATEST GIFT</span></div>
 {stage!=='open'&&<div className="ht-cover" inert={stage!=='closed'} aria-hidden={stage!=='closed'}><div className="ht-cover-inner"><div className="ht-cover-heading"><span className="ht-eyebrow">THE WEDDING CELEBRATION</span><Sparkles size={19} strokeWidth={1}/></div><div className="ht-cover-monogram" aria-hidden="true"><span>{first[0]}</span><i>&</i><span>{second[0]}</span></div><div className="ht-cover-rule"/><p className="ht-cover-names">{first}<i>&</i>{second}</p><p className="ht-cover-date">{dateText(data.date)}</p><button className="ht-open-button" onClick={()=>setStage('opening')}>Open our celebration <ArrowUpRight size={18}/></button><span className="ht-cover-foot">TWO FAMILIES. ONE BEAUTIFUL BEGINNING.</span></div></div>}
 </div>
 {open&&<a className="ht-discover" href="#heritage-countdown">The celebration awaits <ArrowDown size={17}/></a>}
 <span className="sr-only" role="status">{stage==='opening'?'Opening your Heritage invitation…':open?'Your invitation is open.':''}</span>
 </section>
 {open&&<div className="ht-pages">
 <section className="ht-welcome ht-reveal"><span className="ht-eyebrow">A CELEBRATION OF LOVE & TOGETHERNESS</span><h2>Some bonds are<br/><em>made for a lifetime.</em></h2><p>{data.message||'With our families beside us, we invite you to celebrate the beginning of our forever.'}</p><Heart size={20} strokeWidth={1}/>{(data.firstFamily||data.secondFamily)&&<div className="ht-families">{data.firstFamily&&<p>{data.firstFamily}</p>}{data.firstFamily&&data.secondFamily&&<span>&</span>}{data.secondFamily&&<p>{data.secondFamily}</p>}</div>}</section>
 <div id="heritage-countdown" className="ht-countdown ht-reveal"><WeddingCountdown data={data}/></div>
 {data.photo&&<section className="ht-memories ht-reveal"><div className="ht-section-heading"><span className="ht-eyebrow">THE HEART OF OUR STORY</span><h2>In every lifetime,<br/><em>it would be you.</em></h2></div><div className="ht-photo-stage" onPointerMove={tilt} onPointerLeave={reset}><div className="ht-photo-orbit"><div className="ht-photo-back" aria-hidden="true"/><figure className="ht-photo"><img src={data.photo} alt={first+' and '+second+' together'} loading="lazy"/><figcaption><span>{first}</span><Heart size={16} strokeWidth={1}/><span>{second}</span></figcaption></figure></div><span className="ht-photo-caption">A MOMENT TO KEEP. A FOREVER TO COME.</span></div><button className="ht-motion-button" aria-pressed={!motion} onClick={()=>{setMotion(!motion);reset()}}>{motion?<Pause size={14}/>:<Play size={14}/>} {motion?'Pause photo motion':'Resume photo motion'}</button></section>}
 <section className="ht-story ht-reveal"><span className="ht-eyebrow">OUR STORY, SO FAR</span><h2>A thousand little moments.<br/><em>One extraordinary love.</em></h2><p>{data.story||'In the everyday moments, we found our forever. Now we begin a new chapter, surrounded by our favourite people.'}</p><span className="ht-signature">{first} & {second}</span></section>
 <section className="ht-celebrations"><div className="ht-section-heading ht-reveal"><span className="ht-eyebrow">COME, MAKE MEMORIES WITH US</span><h2>The days we’ll<br/><em>remember forever.</em></h2></div><div className="ht-events">{data.events.map((event,i)=><article className="ht-event ht-reveal" key={i}><div className="ht-event-top"><span className="ht-event-number">{String(i+1).padStart(2,'0')}</span><span className="ht-eyebrow">YOU’RE INVITED</span><Sparkles size={19} strokeWidth={1}/></div><h3>{event.name||'Our celebration'}</h3><p className="ht-event-date">{dateText(event.date)}{event.time&&<span>{event.time} · Local venue time</span>}</p><div className="ht-gold-rule"/><h4>{event.venue||'Venue to be announced'}</h4><p>{event.address}</p>{event.address&&<a className="ht-map" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(event.venue+' '+event.address)} target="_blank" rel="noreferrer"><MapPin size={16}/> View location <ArrowUpRight size={16}/></a>}</article>)}</div></section>
 {(data.dressCode||data.accommodation||data.gifts)&&<section className="ht-details ht-reveal"><span className="ht-eyebrow">A FEW LITTLE DETAILS</span>{[['Dress code',data.dressCode],['Your stay',data.accommodation],['Gifts',data.gifts]].map(([label,body])=>body&&<div key={label}><h3>{label}</h3><p>{body}</p></div>)}</section>}
 <section className="ht-finale ht-reveal"><img src="/royal-courtyard.png" alt="" loading="lazy"/><div className="ht-finale-shade"/><div className="ht-finale-copy"><Sparkles size={26} strokeWidth={1}/><span className="ht-eyebrow">WITH FULL HEARTS & OPEN ARMS</span><h2>Our joy is greater<br/><em>with you in it.</em></h2><p>{first} <i>&</i> {second}</p><span className="ht-finale-date">{dateText(data.date)}</span></div></section>
 <footer className="ht-footer"><button onClick={replay}><RotateCcw size={15}/> Open it again</button><a href="/">Wedlink</a><span>MADE FOR YOUR FOREVER.</span></footer>
 </div>}
 </article>
}
