'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Globe2,Heart,Menu,X,MousePointer2,Smartphone,Link2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {templates,example,Invitation,Brand} from './shared';
export default function Home(){const [active,setActive]=useState('All designs');const [preview,setPreview]=useState<string|null>(null);const [menu,setMenu]=useState(false);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();Promise.resolve(context.registerTool({name:'browse_wedding_templates',description:'Filter the visible Wedlink template collection by style.',inputSchema:{type:'object',properties:{style:{type:'string',enum:['All designs','Modern','Romantic','Indian']}},required:['style'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({style}:any)=>{if(!['All designs','Modern','Romantic','Indian'].includes(style))throw Error('Unknown style');setActive(style);document.getElementById('collection')?.scrollIntoView();return {style,templates:templates.filter(t=>style==='All designs'||t.category===style).map(t=>t.name)};}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
return <><div className="announcement">A little link. A lifetime of memories.</div><header className="nav"><Link href="/" aria-label="Wedlink home"><Brand/></Link><nav id="main-navigation" className={menu?'nav-links open':'nav-links'}><a href="#collection" onClick={()=>setMenu(false)}>The collection</a><a href="#how" onClick={()=>setMenu(false)}>How it works</a><a href="#questions" onClick={()=>setMenu(false)}>Questions</a></nav><a className="button small" href="#collection">Create your invitation <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu} aria-controls="main-navigation">{menu?<X/>:<Menu/>}</button></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> FOR THE BEGINNING OF FOREVER</div><h1>Your love story.<br/>Beautifully <em>linked.</em></h1><p>A wedding website that feels like you. Thoughtfully designed, effortlessly personalized, and ready to share with everyone you love.</p><a className="button" href="#collection">Find your invitation <ArrowUpRight size={18}/></a><Link className="text-button" href="/templates/editorial">Take a little peek <ArrowRight size={17}/></Link><div className="hero-notes"><span><Check size={15}/> Make it yours in minutes</span><span><Check size={15}/> One link for every guest</span></div></div><div className="hero-art"><div className="art-caption">YOUR NEXT CHAPTER STARTS HERE</div><div className="hero-invite"><div className="invite-label">TOGETHER WITH OUR FAMILIES</div><h2>Aarav <i>&</i> Meera</h2><p>ARE GETTING MARRIED</p><div className="hero-photo"><img src="/wedding.png" alt="A couple celebrating together in a sunlit garden"/></div><div className="hero-date"><span>DECEMBER</span><strong>12</strong><span>UDAIPUR, INDIA</span></div><div className="tiny-rule"/><p>We saved you a place in our forever.</p></div><div className="floating-note"><Heart size={18}/><span>A little more you.<br/><strong>A lot more meaningful.</strong></span></div><span className="art-bottom">DESIGNED FOR LOVE. MADE FOR SHARING.</span></div></section>
<div className="feature-strip"><span><Globe2 size={19}/> Love has no borders</span><span><Smartphone size={19}/> Beautiful on every screen</span><span><MousePointer2 size={19}/> No design skills needed</span><span><Link2 size={19}/> All the details. One link.</span></div>
<section className="collection section" id="collection"><div className="section-top"><div><span className="eyebrow">THE WEDLINK COLLECTION</span><h2>A design for <em>your kind of love.</em></h2></div><p>From quiet elegance to a grand celebration.<br/>Find the one that feels like you.</p></div><Tabs value={active} onValueChange={setActive}><TabsList className="filters">{['All designs','Modern','Romantic','Indian'].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList>{['All designs','Modern','Romantic','Indian'].map(x=><TabsContent key={x} value={x}><div className="template-grid">{templates.filter(t=>x==='All designs'||t.category===x).map(t=><article className="template-card" key={t.id}><button className={'template-preview '+t.id} onClick={()=>t.id==='rose-letter'?location.assign('/templates/rose-letter'):t.id==='royal'?location.assign('/templates/royal-courtyard'):t.id==='editorial'?location.assign('/templates/editorial'):t.id==='romance'?location.assign('/templates/garden-romance'):t.id==='heritage'?location.assign('/templates/heritage'):setPreview(t.id)} aria-label={'Preview '+t.name}><div className="template-paper">{t.id==='rose-letter'&&<span className="royal-card-label">OPEN · SCRATCH · DISCOVER</span>}{t.id==='royal'&&<span className="royal-card-label">INTERACTIVE 3D ENTRANCE</span>}<span className="micro">{t.id==='heritage'?'WITH THE BLESSINGS OF OUR FAMILIES':'THE WEDDING OF'}</span><h3>{t.id==='heritage'?'Aarav':'Emma'}<i>&</i>{t.id==='heritage'?'Meera':'Noah'}</h3>{t.id!=='heritage'&&t.id!=='royal'&&t.id!=='rose-letter'&&<img src="/wedding.png" alt="Wedding portrait preview" loading="lazy"/>}<div className="micro">12 · 12 · 2027</div><p>{t.id==='heritage'?'UDAIPUR, INDIA':'TOGETHER IS A BEAUTIFUL PLACE TO BE'}</p></div><span className="preview-badge">Explore design <ArrowUpRight size={15}/></span></button><div className="card-caption"><div><h3>{t.name}</h3><p>{t.subtitle}</p></div><Link href={'/create?template='+t.id} aria-label={'Customize '+t.name}><ArrowUpRight/></Link></div></article>)}</div></TabsContent>)}</Tabs></section>
<section className="how section" id="how"><div><span className="eyebrow">LESS PLANNING. MORE CELEBRATING.</span><h2>From “this is the one”<br/>to <em>“you’re invited.”</em></h2><p>Your names. Your moments. Your celebration.<br/>We bring it all together.</p><a className="text-button" href="#collection">Let’s make it yours <ArrowRight size={18}/></a></div><div className="steps">{[['01','Find your perfect match','Choose a design that captures the spirit of your celebration.'],['02','Tell your story','Add your photo, wedding events, venues, and a few words from the heart. Preview every detail as you go.'],['03','One link. Everyone you love.','Once payment is confirmed, your invitation goes live automatically. Share your link and let the excitement begin.']].map(([n,h,p])=><div className="step" key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section>
<section className="questions section" id="questions"><div><span className="eyebrow">A FEW LITTLE DETAILS</span><h2>Before the <em>big day.</em></h2></div><div>{[['What can I personalize?','Your names, wedding date, welcome message, couple photo, story, and event names, times and venues. Your details appear automatically in the design you choose.'],['Can I see my invitation before paying?','Yes. Personalize your invitation and review the full preview before checkout. Your draft stays private until payment is confirmed.'],['How will my guests open the invitation?','Guests open your invitation link in a browser on their phone, tablet or computer. There is nothing to download.'],['When does my invitation go live?','Your invitation is published automatically after the payment provider confirms successful payment. A pending or unsuccessful payment will not publish your invitation.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="closing"><span className="eyebrow">THE FIRST LOOK AT YOUR FOREVER</span><h2>Make their inbox<br/><em>a little more romantic.</em></h2><a className="button light" href="#collection">Find your invitation <ArrowUpRight size={18}/></a><p>Your story. One beautiful link.</p></section></main><footer><Brand/><span>Thoughtfully made for your together.</span><span>© {new Date().getFullYear()} Wedlink</span></footer>
<Dialog open={!!preview} onOpenChange={o=>!o&&setPreview(null)}><DialogContent className="preview-dialog"><DialogTitle>{templates.find(t=>t.id===preview)?.name} — live preview</DialogTitle><DialogDescription>Sample details. Personalize this design with your own story.</DialogDescription><div className="preview-scroll"><Invitation data={{...example,template:preview||'editorial'}}/></div><Link className="button" href={'/create?template='+preview}>Make this design yours <ArrowUpRight size={18}/></Link></DialogContent></Dialog></>}
