import HeritageInvitation from './heritage-invitation';
import GardenRomance from './garden-romance';
import EditorialInvitation from './editorial-invitation';
import RoseLetter from './rose-letter';
import RoyalCourtyard from './royal-courtyard';
import {MapPin,ArrowUpRight} from 'lucide-react';
export const templates=[{id:'rose-letter',name:'The Rose Letter',category:'Romantic',subtitle:'Envelope opening · Scratch to reveal'},{id:'royal',name:'The Royal Courtyard',category:'Indian',subtitle:'3D palace entrance · Cinematic'},{id:'editorial',name:'The Editorial',category:'Modern',subtitle:'Cinematic opening · Live countdown'},{id:'romance',name:'The Garden Romance',category:'Romantic',subtitle:'3D folding card · Botanical romance'},{id:'heritage',name:'The Heritage',category:'Indian',subtitle:'3D keepsake opening · Royal romance'}];
export type Invite={template:string;first:string;second:string;date:string;message:string;story:string;photo?:string;firstFamily?:string;secondFamily?:string;dressCode?:string;accommodation?:string;gifts?:string;timezone?:string;events:{name:string;date:string;time:string;venue:string;address:string}[]};
export const example:Invite={template:'editorial',first:'Aarav',second:'Meera',date:'2027-12-12',message:'With full hearts and the people we love, we’re beginning our forever. We would love for you to be there.',story:'A chance meeting. A thousand little moments. And a love that feels like coming home. We can’t wait to celebrate our next chapter with you.',photo:'/wedding.png',events:[{name:'The wedding',date:'2027-12-12',time:'16:00',venue:'The Garden Palace',address:'Udaipur, Rajasthan, India'},{name:'Dinner & dancing',date:'2027-12-12',time:'19:00',venue:'The Courtyard',address:'Udaipur, Rajasthan, India'}]};
export function Brand(){return <span className="brand"><img src="/logo.svg" alt=""/><span>Wedlink</span></span>}
export function formatDate(date:string){if(!date)return 'Your wedding date';return new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
export function Invitation({data,invitationId}:{data:Invite;invitationId?:string}){if(data.template==='heritage')return <HeritageInvitation data={data}/>;if(data.template==='romance')return <GardenRomance data={data}/>;if(data.template==='editorial')return <EditorialInvitation data={data}/>;if(data.template==='rose-letter')return <RoseLetter data={data} invitationId={invitationId}/>;if(data.template==='royal')return <RoyalCourtyard data={data}/>;return <article data-long-names={Math.max(data.first.length,data.second.length)>14} className={'invitation '+data.template}><div className="invitation-top"><span className="eyebrow">TOGETHER WITH OUR FAMILIES</span><h1>{data.first||'Your name'}<i>&</i>{data.second||'Your partner'}</h1><p className="spaced">ARE GETTING MARRIED</p>{data.photo&&<img className="couple-photo" src={data.photo} alt={data.first+' and '+data.second}/>}<p className="invitation-date">{formatDate(data.date)}</p><div className="tiny-rule"/><p className="welcome">{data.message}</p></div>{data.story&&<section><span className="eyebrow">A LITTLE ABOUT US</span><h2>Our kind of <em>forever.</em></h2><p>{data.story}</p></section>}<section><span className="eyebrow">LET’S CELEBRATE TOGETHER</span><h2>The <em>celebration.</em></h2><div className="event-list">{data.events.map((e,i)=><div className="event" key={i}><span className="eyebrow">0{i+1}</span><h3>{e.name}</h3><p>{formatDate(e.date)}{e.time?' · '+e.time:''}</p><strong>{e.venue}</strong><p>{e.address}</p>{e.address&&<a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(e.venue+' '+e.address)} target="_blank" rel="noreferrer"><MapPin size={15}/> View location <ArrowUpRight size={15}/></a>}</div>)}</div></section><section><h2>We can’t wait<br/>to celebrate <em>with you.</em></h2><p>{data.first} & {data.second}</p></section><div className="invitation-credit">MADE WITH LOVE, ON <a href="/">WEDLINK</a></div></article>}
